# Generated by Django 5.0.6 on 2024-06-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='selling_price',
            field=models.FloatField(verbose_name='selling price'),
        ),
    ]
